### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by dsadinoff** [KosherJava/zmanim#106]
per https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/hebrewcalendar/JewishCalendar.java

>  The methods used to obtain the parsha were derived from the source code of <a
>  href="http://www.sadinoff.com/hebcal/">HebCal</a> by Danny Sadinoff and JCal for the Mac by Frank Yellin. Both based
>  their code on routines by Nachum Dershowitz and Edward M. Reingold. The class allows setting whether the parsha and
>  holiday scheme follows the Israel scheme or outside Israel scheme. The default is the outside Israel scheme.

I understand that KosherJava started out as GPL, but is now LGPL.  Can you describe how that jibes with the GPL nature of the code used here?

**Comment by KosherJava** [comment]
@dsadinoff 
I thank you for bringing this to my attention. I had years ago requested permission from Avrom Finkelstien when I moved this from a GPL to LGPL not realizing that the code he used was under the GPL. I would like your permission to continue releasing this under the LGPL. If that is not possible I will separate this portion of the code out of the main library, and allow a separate GPL package for the parsha functionality.
Thanks

**Comment by dsadinoff** [comment]
Due to the history of the hebcal codebase, re-licensing is not an option without permissions from Dershowitz, Reingold, Stallman and perhaps the GNU Foundation, so I wouldn't count on it, sorry.

**Comment by KosherJava** [comment]
@dsadinoff
Understood. It will take some time (probably a week) until I get to to separating it.
 would like to take the time to thank you for your pioneer work in open sourcing work so useful for Jews around the world. I don't think the landscape of open source Jewish software would be where it is today if not for your work.

**Comment by dsadinoff** [comment]
My pleasure.  Cheers!

**Comment by KosherJava** [comment]
@dsadinoff,
It took much longer than anticipated to get this done. You can see the results in commit 750f7d6. 
Thank you for your patience.

**Comment by dsadinoff** [comment]
Roger that.  Thanks.
