### ISSUE TITLE
Bug in day of year calculation

### ISSUE THREAD

**Issue by BehindTheMath** [KosherJava/zmanim#110]
`SunTimesCalculator.getDayOfYear()` calculates the day of the year for a specific date ([here](https://astronomy.stackexchange.com/a/2409) is an explanation how it works).  
The code is originally from [Kevin Boone](http://web.archive.org/web/20020511184550/http://www.kevinboone.com:80/suntimes.html). It doesn't appear that his code is online, but it can be downloaded [here](http://kevinboone.net/README_android_suntimes.html).

[Line 117](https://github.com/KosherJava/zmanim/blob/dd2ec5d92c23282d2ca6ab7047bbe31614ac3993/src/net/sourceforge/zmanim/util/SunTimesCalculator.java#L117) is used to account for leap years:
```java
int n3 = (1 + ((year - 4 * (year / 4) + 2) / 3));
```
However, this expression will always evaluate to `1.666667`, which is truncated to `1` when assigned to an `int`. If this code is constant `1`, it's not accounting for anything.

Kevin Boone writes that his algorithms are based on the ones in the [US Naval Observatory's Almanac for Computers (1990)](https://babel.hathitrust.org/cgi/pt?id=uiug.30112105115718;view=1up;seq=21;size=125). Looking there, it's evident that his code is missing something. The formula there has 2 extra places where the decimal is truncated, which in Java would be a cast to `int`:
```java
int n3 = (1 + (int)((year - 4 * (int)(year / 4) + 2) / 3));
```
This code works correctly, because now `n3 == 2` in non-leap years.

However, the Almanac also states that this formula will not work for centurial years not evenly divisible by 400, e.g. 1900 and 2100.  
As a result, it would probably be better to replace this entire formula with Java's `Calendar.get(Calendar.DAY_OF_YEAR)`, which serves the same purpose, as mentioned in [the method's Javadoc](https://github.com/KosherJava/zmanim/blob/dd2ec5d92c23282d2ca6ab7047bbe31614ac3993/src/net/sourceforge/zmanim/util/SunTimesCalculator.java#L112).

**Comment by BehindTheMath** [comment]
Turns out I was wrong.

Since all the numbers are integers, Java does integer arithmetic, and implicitly casts the results to `int`. As a result, it is unnecessary to cast it manually.

This would not necessarily be true for other languages, though. JS, for example, does not have separate types for integers and floats.

**Comment by KosherJava** [comment]
@BehindTheMath,
The change although unneeded at the end, will make it more likely that people who port it to other languages will do it correctly.
