### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ElectrojoDEV** [KosherJava/zmanim#115]
Whats the license of this library, i cant find one

**Comment by KosherJava** [comment]
The library is released under the LGPL license. It is listed in every single source code file. See the source of the [ComplexZmanimCalendar]( https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/ComplexZmanimCalendar.java) as an example. A sub-module for Parsha calculation may be released under the GPL in the future.

**Comment by KosherJava** [comment]
To make it clearer to others, I [updated](https://github.com/KosherJava/zmanim/commit/cd41836b20791037e516d086bd3df6b27589e58e) the [README](https://github.com/KosherJava/zmanim/blob/master/README.md) to clarify that it is released under the LGPL 2.1.
