### ISSUE TITLE
Calculations for far east Time Zones (e.g. +14:00) are one day off

### ISSUE THREAD

**Issue by pinnymz** [KosherJava/zmanim#117]
Calculations for the time of a given solar transition is largely based on coordinates for the given date at GMT which is further offset to a major degree by longitude.  If the longitude is East of 0 (positive), the time will be advanced. If the longitude is West of 0 (negative), the time will be pushed back.

However, there is a unique case where the time actually advances where the longitude is West of 0 - and that is in locations with Time Zones that cross over the antimeridian.  One example of this is Apia, Samoa (-13.8599098,-171.8031745) which has a West longitude but uses a timezone of +14:00.  (There are several other examples, this is just the most extreme).  

When the date is '2017-10-15' in Apia, there are other locations at roughly the same longitude (for example Pago Pago) that are observing a date of '2017-10-14'.  Conversely, when Pago Pago is observing '2017-10-15', Apia is already observing '2017-10-16'.

Asking the calculator to give us the zmanim for 2017-10-15 in Apia will actually produce the zmanim that reflect where the sun would be in Apia when it is 10-15 in a place like Pago Pago. By this time, it is actually 10-16 in Apia.  However, the logic coerces the date to 10-15 without regard for this discrepancy.

I believe the correct behavior in this scenario would be to ask the calculator to operate using 10-14.  The UTC time returned will correctly adjust to 10-15 when the +14:00 offset is applied.  The trick would be in recognizing this scenario.

**Comment by pinnymz** [comment]
@KosherJava - to elaborate on how this can be done, see [here](https://github.com/pinnymz/ruby-zmanim/blob/master/lib/zmanim/util/geo_location.rb#L77) for a method that detects an antimeridian crossover (like Apia, Samoa).  This method can be used to [adjust the given date](https://github.com/pinnymz/ruby-zmanim/blob/master/lib/zmanim/astronomical_calendar.rb#L46) before applying the desired algorithm, using a [wrapper method](https://github.com/pinnymz/ruby-zmanim/blob/master/lib/zmanim/astronomical_calendar.rb#L77).

**Comment by KosherJava** [comment]
Closed by be24d1d. Thank you @pinnymz
