### ISSUE TITLE
JewishCalendar computes some dates wrong?

### ISSUE THREAD

**Issue by nafg** [KosherJava/zmanim#121]
To reproduce:

```java
new JewishCalendar(new GregorianCalendar(1582, 9, 14))
```

Expected: 18 Tishrei 5343 (via [Rosetta Calendar](http://www.rosettacalendar.com/))
Got: 28 Tishrei 5343

**Comment by pnemonic78** [comment]
Chabad calculates differently:
http://www.jrcc.org/calendar/1000year.asp?tdate=10/14/1584
Sunday, October 14, 1584 ->  Cheshvan 9, 5345*
***IMPORTANT**: This calculation may be off by a day, click here for more information.

**Comment by KosherJava** [comment]
@nafg from the [Wikipedia Gregorian calendar entry](https://en.wikipedia.org/wiki/Gregorian_calendar#Preparation)

> When the new calendar was put in use, the error accumulated in the 13 centuries since the Council of Nicaea was corrected by a deletion of 10 days. The Julian calendar day Thursday, 4 October 1582 was followed by the first day of the Gregorian calendar, Friday, 15 October 1582

I think that this explains the discrepancy that you mentioned, and is more accurate than a raw calculation done by other libraries. Do you agree with this?

**Comment by pnemonic78** [comment]
https://www.hebcal.com/converter/?gd=15&gm=10&gy=1582&g2h=1
Fri, 15 October 1582 = 19th of Tishrei, 5343

**Comment by KosherJava** [comment]
@nafg do you see any reason to keep this open given that the date predates the Gregorian calendar?

**Comment by KosherJava** [comment]
Closing based on comments above.
