### ISSUE TITLE
Daf Yomi miscalculation

### ISSUE THREAD

**Issue by pinnymz** [KosherJava/zmanim#126]
Per https://github.com/hebcal/hebcal-js/issues/47, there seems to be a miscalculation for when Midos starts.

https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/hebrewcalendar/YomiCalculator.java#L107
I believe the fix would as simple as changing this line to read `blatt += 32;`

**Comment by JosephSilber** [comment]
@KosherJava unfortunately, the fix isn't enough, since the dafim are now out of sync. Tamid is still marked as having 10 dafim, but it doesn't.

See the actual list of dafim that I posted in the [original issue](https://github.com/hebcal/hebcal-js/issues/47#issuecomment-393012905).

**Comment by Yitzchok** [comment]
This is the fix I used in the .Net project

https://github.com/Yitzchok/Zmanim/commit/aa3d20433d8541d8d96611022287bdaf4dc78134
