### ISSUE TITLE
Negative elevation.

### ISSUE THREAD

**Issue by pnemonic78** [KosherJava/zmanim#132]
Why are negative elevations illegal in `net.sourceforge.zmanim.util.GeoLocation` ?
Should work for locations at Dead Sea (-400m).

**Comment by KosherJava** [comment]
@pnemonic78 , Negative elevation such as the Dead Sea are impacted by obstructions in elevation. To just use a negative elevation and not change the radius of the earth would not work. The elevation calculations adjust the horizon view from elevation, something that is impossible without shrinking the earth radius. I know of no posking who agree to this.  As far as obstructions on the horizon, that is something not currently supported by the library. In short, negative elevation would produce incorrect results.

**Comment by KosherJava** [comment]
@pnemonic78 , please let me know if you agree that this can be closed.

**Comment by KosherJava** [comment]
@pnemonic78 Please feel free to reopen if you feel that this is still an issue and have sources for negative elevation calculation.
