### ISSUE TITLE
My timezone

### ISSUE THREAD

**Issue by kvyatek83** [KosherJava/zmanim#136]
I want to see the zmanim of Hifa in israel but i can't make the right req, what is the correct url plz??

**Comment by KosherJava** [comment]
Please clarify what the issue is. Have you reviewed https://kosherjava.com/zmanim-project/how-to-use-the-zmanim-api/ and https://kosherjava.com/2011/11/08/outputting-zmanim-for-a-different-time-zone-with-the-the-zmanim-api/ ?

**Comment by KosherJava** [comment]
Closed due to lack of feedback
