### ISSUE TITLE
default AstronomicalCalculator

### ISSUE THREAD

**Issue by msalle** [KosherJava/zmanim#137]
I was wondering why the SunTimesCalculator() is the default calculator in [AstronomicalCalculator.java lines 83-85](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/util/AstronomicalCalculator.java#L83_L85) instead of the more precise NOAACalculator() ? The latter, for example, makes a difference between years, while the former just returns the same zmanim every year (counting the days from 1 January).

**Comment by KosherJava** [comment]
@msalle , 
There is no good reason to have the USNO algorithm as the default, and I actually changed the default in https://kosherjava.com/zmanim-project/zmanim-calendar-generator/ . In the past, people knew of the USNO charts and were more comfortable with that one. I will hopefully change the default in the near future.

**Comment by msalle** [comment]
That makes sense, thanks.
Mischa

**Comment by BehindTheMath** [comment]
@KosherJava Can this be closed? I believe this was resolved by b69dc31c.

**Comment by KosherJava** [comment]
Closing this as done.
