### ISSUE TITLE
improving getSunTransit() depending on AstronomicalCalculator

### ISSUE THREAD

**Issue by msalle** [KosherJava/zmanim#138]
The current [ZmanimCalendar#getChatzos()](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/ZmanimCalendar.java#L228_L242) uses the midpoint between sunrise and sunset (see [AstronomicalCalendar.java#getSunTransit()](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/AstronomicalCalendar.java#L502_L527)). As you say, this is following **most**  opinions. On the other hand, I have found some poskim actually using the real transit time for their calculation and it would be very useful to have access to it.
Using the [NOAACalculator#getSolarNoonUTC()](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/util/NOAACalculator.java#L468_L491) an actual transit calculation is available, but given that it is a private method, it cannot be accessed externally.
I would suggest to:

1. change  [ZmanimCalendar#getChatzos()](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/ZmanimCalendar.java#L228_L242) to there calculate use the sunrise and sunset instead of calling getSunTransit()
2. to create a getSunTransit() in each AstronomicalCalculator implementation
3. to redefine the [AstronomicalCalendar.java#getSunTransit()](https://github.com/KosherJava/zmanim/blob/master/src/net/sourceforge/zmanim/AstronomicalCalendar.java#L502_L527) to calculate using a call to the getSunTransit() in the underlying AstronomicalCalculator.
4. or as alternative to 2. and 3. provide a default in AstronomicalCalculator itself which can then be overridden in e.g. NOAACalculator

**Comment by KosherJava** [comment]
@msalle , better late than never. This is fully in place and was included in the [2.5.0 release](https://github.com/KosherJava/zmanim/releases/tag/2.5.0).

**Comment by msalle** [comment]
> @msalle , better late than never. This is fully in place and was included in the [2.5.0 release](https://github.com/KosherJava/zmanim/releases/tag/2.5.0).

Great, many thanks!
