### ISSUE TITLE
Add CI with GitHub Actions to automatically run the unit tests

### ISSUE THREAD

**Issue by BehindTheMath** [KosherJava/zmanim#151]
If the unit tests pass, GitHub Actions can be set up to automatically run them on each push, PR, etc.

**Comment by KosherJava** [comment]
Closed via https://github.com/KosherJava/zmanim/commit/c013b77 . Thanks @BehindTheMath  for the request, and to @elijulian for the actual implementation. It is now time to really start adding test cases.
