### ISSUE TITLE
Potential NullPointerExceptions

### ISSUE THREAD

**Issue by BehindTheMath** [KosherJava/zmanim#154]
* [Zman.DATE_ORDER](https://github.com/KosherJava/zmanim/blob/39b5d9ef25910989e3b409b187962d8c6388ba59/src/net/sourceforge/zmanim/util/Zman.java#L70) - Since `Date` is nullable, `getZman()` can return null.
* [Zman.NAME_ORDER](https://github.com/KosherJava/zmanim/blob/39b5d9ef25910989e3b409b187962d8c6388ba59/src/net/sourceforge/zmanim/util/Zman.java#L70) - Since `String` is nullable, `getZmanLabel()` can return null.

**Comment by KosherJava** [comment]
Thank you @BehindTheMath. Do you think that nulls should be sorted first or last?

**Comment by BehindTheMath** [comment]
I think first.

**Comment by BehindTheMath** [comment]
Here's another one: [ZmanimCalendar.isAssurBemlacha()](https://github.com/KosherJava/zmanim/blob/495d45f3f2b216e0416088a8bf387e8ce2e34fc0/src/net/sourceforge/zmanim/ZmanimCalendar.java#L680)

**Comment by KosherJava** [comment]
> Here's another one: [ZmanimCalendar.isAssurBemlacha()](https://github.com/KosherJava/zmanim/blob/495d45f3f2b216e0416088a8bf387e8ce2e34fc0/src/net/sourceforge/zmanim/ZmanimCalendar.java#L680)

@BehindTheMath, as per our discussion, his is much more than a null pointer vulnerability, and it may nor be something that we want to fix. Let's be in touch.
