### ISSUE TITLE
Create jar file

### ISSUE THREAD

**Issue by Idan-Neeman** [KosherJava/zmanim#158]
Hey,
I'm trying to create JAR file from this library to use the last version in my android app, but I get JAR file with errors, so I can't use it.
Maybe do you can please to add explaination how to use this code library in java/android project or how to create JAR file?

Thanks

**Comment by KosherJava** [comment]
@Idan-Neeman , 
I have never developed for Android, but have a look at https://github.com/KosherJava/zmanim/blob/master/build/build.xml . While Ant https://ant.apache.org/ may not be considered cutting edge, it does the trick. Please let me know if this solves your issues.

**Comment by KosherJava** [comment]
@Idan-Neeman ,
Now that Maven is in place, go to https://search.maven.org/artifact/com.kosherjava/zmanim , select the latest version and on the top right there is a link to download the Jar.
