### ISSUE TITLE
Some possible typos in the documentation

### ISSUE THREAD

**Issue by chacham2** [KosherJava/zmanim#170]
Looking at [Class HebrewDateFormatter](https://kosherjava.com/zmanim/docs/api/com/kosherjava/zmanim/hebrewcalendar/HebrewDateFormatter.html) (while wondering if the class provides hebrew text for the schedule times, like Alos and Chatzos)

"the The list"  The first "the" is redundant. This shows up twice.
ניצבים I believe there is no yud between the nun and tsadi.

Why is it פורים שושן and not the other way around? Same for "פורים שושן קטן". The English has it the other way around.

**Comment by KosherJava** [comment]
@chacham2, thanks for pointing these out. The class was not designed to format "labels", but for the values. Maybe at a future point I will add support, but it would not exactly fit into this class smoothly. In the https://kosherjava.com/zmanim-project/zmanim-calendar-generator/ I do have some code that does have Hebrew and English labels, but it is messy and does not fit into this class. I am open to suggestions.
I corrected the spelling for נצבים and removed the extra "the" in 5733b14. As far as פורים שושן VS שושן פורים , This really boils down to Yiddish VS Hebrew conventions, and the Hebrew formatting is mostly targeted at Israel so it was done this way. In English it is almost always referred to as Shushan Purim (from the Yiddish). You can easily override this if you want the "Yiddish" version. 
Have a Gutten Moed.

**Comment by KosherJava** [comment]
@chacham2 , see https://hebrew-academy.org.il/2017/03/08/%D7%A9%D7%95%D7%A9%D7%9F-%D7%A4%D7%95%D7%A8%D7%99%D7%9D-%D7%90%D7%95-%D7%A4%D7%95%D7%A8%D7%99%D7%9D-%D7%A9%D7%95%D7%A9%D7%9F/ for more on this. I am open to change things (despite having closed it here). I will try to open a discussion on this on the Zmanim slack channel. You can [contact me directly](https://kosherjava.com/contact/) to continue this discussion if you would like.

**Comment by chacham2** [comment]
>In the https://kosherjava.com/zmanim-project/zmanim-calendar-generator/ I do have some code that does have Hebrew and English labels, but it is messy and does not fit into this class. I am open to suggestions.

Should i open a new issue to start a discussion on it? I have some ideas, but who doesn't?

**Comment by KosherJava** [comment]
@chacham2, Please feel free to open a new issue for that.
