### ISSUE TITLE
HebrewDateFormatter for JewishCalendar via ikvm, what needs to be set?

### ISSUE THREAD

**Issue by chacham2** [KosherJava/zmanim#172]
I'm trying to use HebrewDateFormatter. Note, this is in vb.net via ikvm.

```
        Dim Formatter As New HebrewDateFormatter
        Dim Luach As New JewishCalendar
        Dim Yom As New JewishDate

        Formatter.setHebrewFormat(True)
        Debug.WriteLine(Yom)
        Debug.WriteLine(Formatter.format(Yom))
        Debug.WriteLine(Formatter.formatDayOfWeek(Yom))

        Debug.WriteLine(Luach)
        Debug.WriteLine(Formatter.formatParsha(Luach))
        Debug.WriteLine(Formatter.formatRoshChodesh(Luach))
```
The output is:

11 Iyar, 5781
י״א אייר תשפ״א
ששי
11 Iyar, 5781

So, the formatter for JewishDate seems to be working but not for JewishCalendar. I am trying to figure out what i am doing wrong. Is there another parameter for JewishCalendar that needs to be set before trying to format it?

**Comment by KosherJava** [comment]
@chacham2 ,
Please see the documentation for [getParsha()](https://kosherjava.com/zmanim/docs/api/com/kosherjava/zmanim/hebrewcalendar/JewishCalendar.html#getParshah()). When it is not Shabbos, Parsha.NONE is returned, and the formatter formats this as an empty string. The same for [formatRoshChodesh() ](https://kosherjava.com/zmanim/docs/api/com/kosherjava/zmanim/hebrewcalendar/HebrewDateFormatter.html#formatRoshChodesh(com.kosherjava.zmanim.hebrewcalendar.JewishCalendar)) that returns an empty string when it is not _Rosh Chodesh_.  I know that some in the past have expected the _parsha_ returned in middle of the week, but that is not how this API was designed. What output did you expect for formatting a _Rosh Chodesh_ when it is in middle of the month? For additional info, please see documentation in the the [source code](https://github.com/KosherJava/zmanim/blob/master/src/main/java/com/kosherjava/zmanim/hebrewcalendar/HebrewDateFormatter.java).

Have a good Shabbos.

**Comment by chacham2** [comment]
And here i thought i looks at the documentation. Maybe i looked in the wrong area?

>What output did you expect for formatting a Rosh Chodesh when it is in middle of the month? 

The real answer is that i was just trying a couple to see what worked and what did not. So, i just tried a couple calls and saw they did not work. But from the name of the call, i would have expected the month's rosh chodesh, whenever it was.

>I know that some in the past have expected the parsha returned in middle of the week, but that is not how this API was designed.

That is indeed what i would have expected. The names of the calls don't make it so clear what is being returned. I guess i can test what day of the week it is and add the days until Shabbos.

In any case i don't mean to complain, this is a wonderful library. Have a good Shabbos!

**Comment by chacham2** [comment]
And here i thought i looks at the documentation. Maybe i looked in the wrong area?

>What output did you expect for formatting a Rosh Chodesh when it is in middle of the month? 

The real answer is that i was just trying a couple to see what worked and what did not. So, i just tried a couple calls and saw they did not work. But from the name of the call, i would have expected the month's rosh chodesh, whenever it was.

>I know that some in the past have expected the parsha returned in middle of the week, but that is not how this API was designed.

That is indeed what i would have expected. The names of the calls don't make it so clear what is being returned. I guess i can test what day of the week it is and add the days until Shabbos.

In any case i don't mean to complain, this is a wonderful library. Have a good Shabbos!

**Comment by KosherJava** [comment]
No worries.
