### ISSUE TITLE
License under Apache or MIT License?

### ISSUE THREAD

**Issue by cgivre** [KosherJava/zmanim#184]
BS''D 
Hi there!  Thank you for writing this really useful library.  I wanted to ask if you would consider releasing it under the Apache 2.0 or MIT license? 

If we wanted to include your library in an Apache or other OSS licensed product, it might be difficult to do so. 
Thanks!

**Comment by KosherJava** [comment]
@cgivre ,
Changing the license for compatibility with Apache 2.0 or MIT licenses is not going to happen at the moment for two reasons. For one, there are too many contributors who would have to agree to such a change and chasing them down would not be trivial. Secondly, part of why I chose the LGPL (it was initially GPL) was to enforce that if anyone did make changes to the zmanim code, those changes would benefit everyone else. The Apache 2.0 or MIT licenses would not require that modifications to the core zmanim code be made available. Feel free to comment, but I am closing this issue now.
