### ISSUE TITLE
check for machar_rosh_chodesh accounts for wday?

### ISSUE THREAD

**Issue by emaayan** [KosherJava/zmanim#202]
i don't understand this code, cause it looks like it accounts if it's weekdays and only if it's not, it would accont for it. 
without this check i would check , i would get "מחר ר"ח " as the image displayed. 
`yomtov getmacharchodesh(hdate date)
{
	if (date.wday)
	{
		return CHOL;
	}
	if (date.day == 30 || date.day == 29)
	{
		return MACHAR_CHODESH;
	}
	return CHOL;
}`

![image](https://user-images.githubusercontent.com/13434544/215279534-25f81c2d-e9ac-4698-afc1-c326eeec85bd.png)

**Comment by KosherJava** [comment]
@emaayan ,
I apologize for the long delay in replying. This method returns if the _hafrorah_ of the week is _Machar Chodesh_, not if it is _erev Rosh Chodesh_. What you are looking for is [isErevRoshChodesh()](https://github.com/KosherJava/zmanim/blob/master/src/main/java/com/kosherjava/zmanim/hebrewcalendar/JewishCalendar.java#L1042).
