### ISSUE TITLE
Wrong formatter used on test output - LOW priority  

### ISSUE THREAD

**Issue by elazarrosenthal** [KosherJava/zmanim#205]
Formatting Bavli daf with Yerushalmi For matter

Working on adding some tests 
I noticed the output formatting is not going to work in some tests ( one example blow others in same file)

I assume the assert part of the test is correct 
but anyone looking at the output is going to see junk

src/test/java/com/kosherjava/zmanim/hebrewcalendar/YomiCalculatorTest.java

	@Test
	public void testCorrectDaf2() {
		JewishCalendar jewishCalendar = new JewishCalendar(5736, JewishDate.ELUL, 26);
		Daf daf = YomiCalculator.getDafYomiBavli(jewishCalendar);
		Assert.assertEquals(4, daf.getMasechtaNumber());
		Assert.assertEquals(14, daf.getDaf());
		System.out.println(hdf.formatDafYomiYerushalmi(jewishCalendar.getDafYomiBavli()));
	}

**Comment by Elyahu41** [comment]
Is hdf defined in the class?

**Comment by elazarrosenthal** [comment]
The code works 
I was just reviewing the test to write one of my own and noticed a mismatch on the getdaf and fhe formatter

that means the diagnostic data printed is GIGO 

I put Low Priority for a reason :)
