### ISSUE TITLE
In  getDafYomiYerushalmi() [LastMischta, LastMesechtahMaxDaf + 1] returned for Daf 1 of  Meschtas after Brachos

### ISSUE THREAD

**Issue by elazarrosenthal** [KosherJava/zmanim#207]
I fixed this as part of my pull request 
Newyerushalmi Code to implement New Yerushalmi Yomi
https://github.com/KosherJava/zmanim/pull/206 
But incase you dont want to accept that request 
Beawre that the current implimentation of  YerushalmiYomiCalculator -> getDafYomiYerushalmi()
For Mesectas after the first will returen LastMisectah , LastMisectaMaxDaf+1 
for the 1st daf of a new mesechta

The fix I did is on line 100 			if (total <= BLATT_PER_MASSECTA[j]) {

replace <= with - 

Anotherr fix would be to start the daf counter from not 0 
but I did not try totest such a solution

**Comment by KosherJava** [comment]
@elazarrosenthal ,
Please clarify
`replace <= with -`
Thanks
