### ISSUE TITLE
Add Mizmor Lesoda to TefilaRules

### ISSUE THREAD

**Issue by CompuGenius** [KosherJava/zmanim#218]
In `TefilaRules`, you have Mizmor Lesoda under a TODO. I need it now, so I implemented it like below.

```java
public boolean isMizmorLesodaRecited(JewishCalendar jewishCalendar) {
    int holidayIndex = jewishCalendar.getYomTovIndex();
    return holidayIndex != JewishCalendar.EREV_YOM_KIPPUR && holidayIndex != JewishCalendar.EREV_PESACH && !jewishCalendar.isCholHamoedPesach();
}
```

**Comment by zachweix** [comment]
Should it also check that it isn't Shabbos or Yom Tov?

**Comment by CompuGenius** [comment]
> Should it also check that it isn't Shabbos or Yom Tov?

I suppose, but I don't see a use-case for checking `isMizmorLesodaRecited` except in a weekday Siddur - I don't think shul screens would be displaying it if it's said. Up to @KosherJava if he thinks it should check for that or not.

**Comment by zachweix** [comment]
I hear, but it doesn't really cost too much extra in the method. With that said, I've seen shul boards say on shabbos "no tachanun", so it is theoretically possible (?)

**Comment by KosherJava** [comment]
@CompuGenius  and @zachweix,
Even if not used, it should not return true for Shabbos since it is incorrect. I will hopefully add this sometime this week.

**Comment by CompuGenius** [comment]
> @CompuGenius and @zachweix, Even if not used, it should not return true for Shabbos since it is incorrect. I will hopefully add this sometime this week.

That's true. Alright, awesome 👍
Thanks for the shout-out in the changelogs of 2.5.0 btw, was a pleasant surprise when I happened to check it today 😊

**Comment by KosherJava** [comment]
Adding a check for `isAssurBemelacha()` should do the trick. Something like:

> `return holidayIndex != isAssurBemelacha() && != JewishCalendar.EREV_YOM_KIPPUR && holidayIndex != JewishCalendar.EREV_PESACH && !jewishCalendar.isCholHamoedPesach();`

**Comment by KosherJava** [comment]
There seems to be some differences between Ashkenazi and Sephardi _minhagim_ for [Mizmor Lesoda](https://halachipedia.com/index.php?title=Pesukei_DeZimrah#Mizmor_Letodah). Nothing is ever simple.
