### ISSUE TITLE
Shushan Purim Katan is misspelled in Hebrew

### ISSUE THREAD

**Issue by Elyahu41** [KosherJava/zmanim#235]
https://github.com/KosherJava/zmanim/blob/328eee8810a1190c3f55080e6ac3b265e86620a5/src/main/java/com/kosherjava/zmanim/hebrewcalendar/HebrewDateFormatter.java#L442

If you look at this array, it contains an entry for Shushan Purim and Shushan Purim Katan.

However, it is spelled as "פורים שושן" and "פורים שושן קטן".

It should instead be "שושן פורים" and "שושן פורים קטן"

**Comment by KosherJava** [comment]
@Elyahu41 , Shushan Purim is from Yiddish, while in Hebrew my understanding is that is is Purim Shushan. Thoughts?

**Comment by zachweix** [comment]
Per Wikipedia (https://he.wikipedia.org/wiki/%D7%A4%D7%95%D7%A8%D7%99%D7%9D) it is Purim Dimokfim or Shushan Purim

**Comment by KosherJava** [comment]
Later in that article is states
"פורים דמוקפים" או "פורים שושן" (או בעקבות] ה[יידיש]("שושן פורים"

**Comment by Elyahu41** [comment]
@KosherJava I personally have never heard people call it Purim Shushan, and if I did it was maybe a one time thing. Majority of the time I have heard people call it Shushan Purim.

I don't know if I may be wrong and really the majority do call it Purim Shushan. But it seems to me like people expect it to say Shushan Purim. I simply recommended the change because a user went out of their way to tell me that it was incorrect and it should be Shushan Purim. If not for that, I wouldn't have said anything. Although, at first glance, I did think it looked weird.

It's up to you to change it. You could also make a poll on the slack group to see what the minhag is.
