### ISSUE TITLE
VBA and VB6 port - vbzmanim

### ISSUE THREAD

**Issue by diaphone1** [KosherJava/zmanim#236]
Hi
I'm working on porting the zmanim library to VBA (and Visual Basic 6), It's mostly based on yparitcher's C port libzmanim (as I personally prefer procedural code...)

The repo is at:
https://github.com/diaphone1/vbzmanim
Two functional samples are included - A macro enabled Excel file and a VB6 sample
If you see it fit, please add to the ports list
Thanks

**Comment by zachweix** [comment]
I didn't actually look at the Excel file, but I think that's so cool to be able to have that!

**Comment by KosherJava** [comment]
Thanks @diaphone1 . I added the link to the list o ports in the README.
